<?php
// auto-generated by sfPropelAdmin
// date: 2007/02/28 15:01:48
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('../sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'alumno/edit?id='.$alumno->getId()) ?></li>
  <li><?php echo link_to(image_tag('../sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'alumno/delete?id='.$alumno->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
    </ul>
</td>
