generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Llamadoa
    theme:            default
    fields:
          turno: { name: Turno }
          fk_llamados_id: { name: LLamado Actual }
          llamado: { name: habilitar? }
    list:
          title: "Habilitar Alumno a Rendir o Cursar"
          display: [ llamado ]
    edit:
          title: "Habilitacion a Rendir en Autogestion "
          display:
              " ":  [fk_llamados_id,  llamado]
          actions:
              _save: -

