generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Rendida
    theme:            default
    fields:
      id:                     { name: ID }
      fk_alumno_id:           { name: Alumno }
      fk_llamada_id:          { name: Llamado }
      matricula:              { name: Matricula }
      fecha:                  { name: Fecha de Emisión }

    list:
      display:        [id, Alumno, matricula, matricula, fecha, fk_llamada_id]
      title:          Inscripci&oacute;n a Rendidas
      layout:         tabular
      actions:
       _create:     { name: Crear}
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
    edit:
      title:          Detalle de Rendida
      display:
        "Encabezado":       [id, Alumno, fecha, matricula]
        "Detalle":          [Matricula]
      actions:
       _list:              { name: Volver al listado }
       _save_and_add:      { name: Guardar y agregar otro }
       _delete:            { name: Borrar }
       _save:              { name: Guardar}
