<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/08/07 00:20:12

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:dbname=idukaye1_sigedu;host=localhost',
  'username' => 'idukaye1_admin',
  'password' => 'jesucristovive1308',
  'enconding' => 'utf8',
  'classname' => 'DebugPDO',
  'datasource' => 'propel',
  'name' => 'propel',
)),);
