<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/08/07 00:20:10
sfConfig::add(array(
  'app_mailer_defaults' => array (
  'connection' => 
  array (
    'type' => 'native',
    'params' => 
    array (
    ),
  ),
  'reply-to' => NULL,
  'return-path' => NULL,
  'cc' => NULL,
  'bcc' => NULL,
  'subject-template' => '%s',
  'i18n-catalogue' => 'messages',
),
  'app_theme' => true,
  'app_alba_menutheme' => 'ThemeAlba',
  'app_alba_tmpdir' => 'tmp',
));
