<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/08/26 23:04:00
$this->security = array (
  'all' => 
  array (
    '.actions' => 
    array (
      'login_module' => 'seguridad',
      'login_action' => 'login',
    ),
  ),
);
