<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/08/07 00:20:14
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    '.actions' => 
    array (
      'login_module' => 'seguridad',
      'login_action' => 'login',
    ),
  ),
);
