<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2019/08/26 22:52:08
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoAlumno2a/actions/actions.class.php');

