<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/08/26 21:49:19
$this->security = array (
  'all' => 
  array (
    '.actions' => 
    array (
      'login_module' => 'seguridad',
      'login_action' => 'login',
    ),
    'is_secure' => true,
    'credentials' => 'usuario',
  ),
);
