<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/08/07 00:20:14
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
