<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2019/08/26 23:04:36
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoBcomuna/actions/actions.class.php');

