generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Intelectual
    theme:            default
    fields:
      id:                     { name: ID }
      nombre:                 { name: Descripción }
      fk_carrera_id:          { name: Carrera }
      anio:                   { name: Año }
      orden:                  { name: Orden } 

    list:
      display:        [nombre, orden, anio]
      max_per_page:   8
      title:          Lista de Materias
      layout:         tabular
      actions:
       _create:     { name: Cancelar}
      object_actions:
        agregar:

