generator:
  class:              sfPropelAdminGenerator
  param:
      model_class:      Alumno
      theme:            default
      fields:
            nombre: { name: Nombres , params: size=64 }
            apellido: { name: Apellido , params: size=64 }
            fk_provincia_id: { name: Provincia }
            fk_estadoalumno_id: { name: Estado }
            fk_tipodocumento_id: { name: Tipo de Documento }
            fecha_nacimiento: { name: Fecha Nacimiento}
            direccion: { name: Direcci&oacute;n , params: size=64}
            ciudad: { name: Ciudad, params: size=64 }
            telefono: { name: Tel&eacute;fono, params: size=20 }
            sexo: { name: Sexo }
            email: { name: Email , params: size=64 }
            nro_documento:  { name: Nro. Documento, params: size=16 }
            activo: { name: ¿Documentaci&oacuten completa? }
            nombre_apellido: { name: Nombre }
            division: { name: Divisi&oacute;n }
            fk_pais_id: { name: Nacionalidad }
            matricula: { name: Matricula }
            adeuda: { name: Pag&oacute;? }
            apellido_materno: { name: Apellido Materno }
            codigo_postal: { name: CP }
            telefono_fijo: { name: Telefono Fijo }
            sexo: { name: Sexo }
            observacion: { name: Observaci&oacute;n }
      list:
            title: "Habilitar Alumno a Rendir o Cursar"
            display: [ matricula, apellido, nombre, nro_documento, fk_estadoalumno_id, adeuda ]
            filters:  [nro_documento ]
            object_actions:
                _edit: -
            max_per_page: 8
      edit:
            title: " "
            fields:
                fk_provincia_id:   { params: include_custom=--Seleccione una Provincia--}
            display:
                "Informacion Personal":  [ apellido, nombre, fk_tipodocumento_id, nro_documento, adeuda ]
            actions:
                _save: -
                _list: -


